/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface NFTTicketGeneratorInterface extends ethers.utils.Interface {
  functions: {
    "adminAddr()": FunctionFragment;
    "changeSlottingFee(uint256)": FunctionFragment;
    "genNFTContract(address,tuple)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "slottingFee()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "adminAddr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changeSlottingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "genNFTContract",
    values: [
      string,
      {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "slottingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "adminAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeSlottingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genNFTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slottingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class NFTTicketGenerator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: NFTTicketGeneratorInterface;

  functions: {
    adminAddr(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "adminAddr()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    changeSlottingFee(
      newSlottingFee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeSlottingFee(uint256)"(
      newSlottingFee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    genNFTContract(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "genNFTContract(address,(string,string,address[],uint256[],uint32,uint32))"(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    slottingFee(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "slottingFee()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  adminAddr(overrides?: CallOverrides): Promise<string>;

  "adminAddr()"(overrides?: CallOverrides): Promise<string>;

  changeSlottingFee(
    newSlottingFee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeSlottingFee(uint256)"(
    newSlottingFee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  genNFTContract(
    client: string,
    baseSettings: {
      name: string;
      symbol: string;
      payees: string[];
      shares: BigNumberish[];
      typeOfNFT: BigNumberish;
      maxSupply: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "genNFTContract(address,(string,string,address[],uint256[],uint32,uint32))"(
    client: string,
    baseSettings: {
      name: string;
      symbol: string;
      payees: string[];
      shares: BigNumberish[];
      typeOfNFT: BigNumberish;
      maxSupply: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  slottingFee(overrides?: CallOverrides): Promise<BigNumber>;

  "slottingFee()"(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    adminAddr(overrides?: CallOverrides): Promise<string>;

    "adminAddr()"(overrides?: CallOverrides): Promise<string>;

    changeSlottingFee(
      newSlottingFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeSlottingFee(uint256)"(
      newSlottingFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    genNFTContract(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "genNFTContract(address,(string,string,address[],uint256[],uint32,uint32))"(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    slottingFee(overrides?: CallOverrides): Promise<BigNumber>;

    "slottingFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    adminAddr(overrides?: CallOverrides): Promise<BigNumber>;

    "adminAddr()"(overrides?: CallOverrides): Promise<BigNumber>;

    changeSlottingFee(
      newSlottingFee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeSlottingFee(uint256)"(
      newSlottingFee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    genNFTContract(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "genNFTContract(address,(string,string,address[],uint256[],uint32,uint32))"(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    slottingFee(overrides?: CallOverrides): Promise<BigNumber>;

    "slottingFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adminAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "adminAddr()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeSlottingFee(
      newSlottingFee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeSlottingFee(uint256)"(
      newSlottingFee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    genNFTContract(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "genNFTContract(address,(string,string,address[],uint256[],uint32,uint32))"(
      client: string,
      baseSettings: {
        name: string;
        symbol: string;
        payees: string[];
        shares: BigNumberish[];
        typeOfNFT: BigNumberish;
        maxSupply: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    slottingFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "slottingFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
